export interface StockSymbol {
    symbol: string;
    name: string;
}

export const SP500_SYMBOLS: StockSymbol[] = [
    { symbol: "NVDA", name: "NVIDIA Corp" },
    { symbol: "AAPL", name: "Apple Inc" },
    { symbol: "MSFT", name: "Microsoft Corp" },
    { symbol: "AMZN", name: "Amazon.com Inc" },
    { symbol: "GOOGL", name: "Alphabet Inc Class A" },
    { symbol: "GOOG", name: "Alphabet Inc Class C" },
    { symbol: "META", name: "Meta Platforms Inc" },
    { symbol: "AVGO", name: "Broadcom Inc" },
    { symbol: "TSLA", name: "Tesla Inc" },
    { symbol: "BRK.B", name: "Berkshire Hathaway Inc" },
    { symbol: "WMT", name: "Walmart Inc" },
    { symbol: "LLY", name: "Eli Lilly & Co" },
    { symbol: "JPM", name: "JPMorgan Chase & Co" },
    { symbol: "V", name: "Visa Inc" },
    { symbol: "XOM", name: "Exxon Mobil Corp" },
    { symbol: "JNJ", name: "Johnson & Johnson" },
    { symbol: "MU", name: "Micron Technology Inc" },
    { symbol: "MA", name: "Mastercard Inc" },
    { symbol: "COST", name: "Costco Wholesale Corp" },
    { symbol: "ORCL", name: "Oracle Corp" },
    { symbol: "ABBV", name: "AbbVie Inc" },
    { symbol: "BAC", name: "Bank of America Corp" },
    { symbol: "HD", name: "Home Depot Inc" },
    { symbol: "PG", name: "Procter & Gamble Co" },
    { symbol: "MRK", name: "Merck & Co Inc" },
    { symbol: "ADBE", name: "Adobe Inc" },
    { symbol: "CRM", name: "Salesforce Inc" },
    { symbol: "CVX", name: "Chevron Corp" },
    { symbol: "KO", name: "Coca-Cola Co" },
    { symbol: "PFE", name: "Pfizer Inc" },
    { symbol: "CMCSA", name: "Comcast Corp" },
    { symbol: "AMD", name: "Advanced Micro Devices Inc" },
    { symbol: "TMO", name: "Thermo Fisher Scientific Inc" },
    { symbol: "PEP", name: "PepsiCo Inc" },
    { symbol: "CSCO", name: "Cisco Systems Inc" },
    { symbol: "ACN", name: "Accenture plc" },
    { symbol: "NFLX", name: "Netflix Inc" },
    { symbol: "DHR", name: "Danaher Corp" },
    { symbol: "INTC", name: "Intel Corp" },
    { symbol: "VZ", name: "Verizon Communications Inc" },
    { symbol: "WFC", name: "Wells Fargo & Co" },
    { symbol: "UNH", name: "UnitedHealth Group Inc" },
    { symbol: "GE", name: "General Electric Co" },
    { symbol: "DIS", name: "Walt Disney Co" },
    { symbol: "PM", name: "Philip Morris International Inc" },
    { symbol: "NEE", name: "NextEra Energy Inc" },
    { symbol: "QCOM", name: "Qualcomm Inc" },
    { symbol: "MCD", name: "McDonald's Corp" },
    { symbol: "TXN", name: "Texas Instruments Inc" },
    { symbol: "UPS", name: "United Parcel Service Inc" },
    { symbol: "HON", name: "Honeywell International Inc" },
    { symbol: "AMGN", name: "Amgen Inc" },
    { symbol: "LOW", name: "Lowe's Companies Inc" },
    { symbol: "COP", name: "ConocoPhillips" },
    { symbol: "BMY", name: "Bristol-Myers Squibb Co" },
    { symbol: "CAT", name: "Caterpillar Inc" },
    { symbol: "UNP", name: "Union Pacific Corp" },
    { symbol: "IBM", name: "International Business Machines Corp" },
    { symbol: "SBUX", name: "Starbucks Corp" },
    { symbol: "GS", name: "Goldman Sachs Group Inc" },
    { symbol: "SPG", name: "Simon Property Group Inc" },
    { symbol: "BA", name: "Boeing Co" },
    { symbol: "AXP", name: "American Express Co" },
    { symbol: "MDLZ", name: "Mondelez International Inc" },
    { symbol: "TJX", name: "TJX Companies Inc" },
    { symbol: "DE", name: "Deere & Co" },
    { symbol: "MMM", name: "3M Co" },
    { symbol: "LMT", name: "Lockheed Martin Corp" },
    { symbol: "CVS", name: "CVS Health Corp" },
    { symbol: "CHTR", name: "Charter Communications Inc" },
    { symbol: "INTU", name: "Intuit Inc" },
    { symbol: "BDX", name: "Becton Dickinson and Co" },
    { symbol: "ADI", name: "Analog Devices Inc" },
    { symbol: "MSI", name: "Motorola Solutions Inc" },
    { symbol: "SO", name: "Southern Co" },
    { symbol: "RTX", name: "Raytheon Technologies Corp" },
    { symbol: "BKNG", name: "Booking Holdings Inc" },
    { symbol: "PLD", name: "Prologis Inc" },
    { symbol: "MO", name: "Altria Group Inc" },
    { symbol: "ISRG", name: "Intuitive Surgical Inc" },
    { symbol: "PNC", name: "PNC Financial Services Group Inc" },
    { symbol: "CI", name: "Cigna Corp" },
    { symbol: "C", name: "Citigroup Inc" },
    { symbol: "SYK", name: "Stryker Corp" },
    { symbol: "AMT", name: "American Tower Corp" },
    { symbol: "NOW", name: "ServiceNow Inc" },
    { symbol: "EQIX", name: "Equinix Inc" },
    { symbol: "VRTX", name: "Vertex Pharmaceuticals Inc" },
    { symbol: "SHW", name: "Sherwin-Williams Co" },
    { symbol: "ELV", name: "Elevance Health Inc" },
    { symbol: "ADP", name: "Automatic Data Processing Inc" },
    { symbol: "CB", name: "Chubb Ltd" },
    { symbol: "MMC", name: "Marsh & McLennan Companies Inc" },
    { symbol: "REGN", name: "Regeneron Pharmaceuticals Inc" },
    { symbol: "GILD", name: "Gilead Sciences Inc" },
    { symbol: "CMG", name: "Chipotle Mexican Grill Inc" },
    { symbol: "DG", name: "Dollar General Corp" },
    { symbol: "CL", name: "Colgate-Palmolive Co" },
    { symbol: "GD", name: "General Dynamics Corp" },
    { symbol: "CCI", name: "Crown Castle Inc" },
    { symbol: "ADSK", name: "Autodesk Inc" },
    { symbol: "TDY", name: "Teledyne Technologies Inc" },
    { symbol: "FISV", name: "Fiserv Inc" },
    { symbol: "ZTS", name: "Zoetis Inc" },
    { symbol: "DUK", name: "Duke Energy Corp" },
    { symbol: "PGR", name: "Progressive Corp" },
    { symbol: "EOG", name: "EOG Resources Inc" },
    { symbol: "APH", name: "Amphenol Corp" },
    { symbol: "NDAQ", name: "Nasdaq Inc" },
    { symbol: "CME", name: "CME Group Inc" },
    { symbol: "ORLY", name: "O'Reilly Automotive Inc" },
    { symbol: "PSX", name: "Phillips 66" },
    { symbol: "ICE", name: "Intercontinental Exchange Inc" },
    { symbol: "CPRT", name: "Copart Inc" },
    { symbol: "KHC", name: "Kraft Heinz Co" },
    { symbol: "ROP", name: "Roper Technologies Inc" },
    { symbol: "LRCX", name: "Lam Research Corp" },
    { symbol: "DD", name: "DuPont de Nemours Inc" },
    { symbol: "PAYX", name: "Paychex Inc" },
    { symbol: "TRV", name: "Travelers Companies Inc" },
    { symbol: "CTAS", name: "Cintas Corp" },
    { symbol: "CDNS", name: "Cadence Design Systems Inc" },
    { symbol: "MCK", name: "McKesson Corp" },
    { symbol: "CLX", name: "Clorox Co" },
    { symbol: "ETN", name: "Eaton Corp plc" },
    { symbol: "FCX", name: "Freeport-McMoRan Inc" },
    { symbol: "HSY", name: "Hershey Co" },
    { symbol: "MAR", name: "Marriott International Inc" },
    { symbol: "ODFL", name: "Old Dominion Freight Line Inc" },
    { symbol: "PCG", name: "PG&E Corp" },
    { symbol: "PX", name: "Praxair Inc" },
    { symbol: "RSG", name: "Republic Services Inc" },
    { symbol: "SBAC", name: "SBA Communications Corp" },
    { symbol: "SLB", name: "Schlumberger NV" },
    { symbol: "SPGI", name: "S&P Global Inc" },
    { symbol: "STZ", name: "Constellation Brands Inc" },
    { symbol: "TGT", name: "Target Corp" },
    { symbol: "VLO", name: "Valero Energy Corp" },
    { symbol: "WELL", name: "Welltower Inc" },
    { symbol: "XEL", name: "Xcel Energy Inc" },
    { symbol: "ZBH", name: "Zimmer Biomet Holdings Inc" },
    { symbol: "ALB", name: "Albemarle Corp" },
    { symbol: "ALK", name: "Alaska Air Group Inc" },
    { symbol: "ALLE", name: "Allegion plc" },
    { symbol: "AMCR", name: "Amcor plc" },
    { symbol: "AOS", name: "A.O. Smith Corp" },
    { symbol: "APA", name: "APA Corp" },
    { symbol: "ATO", name: "Atmos Energy Corp" },
    { symbol: "AWK", name: "American Water Works Company Inc" },
    { symbol: "BKR", name: "Baker Hughes Co" },
    { symbol: "BLL", name: "Ball Corp" },
    { symbol: "BRO", name: "Brown & Brown Inc" },
    { symbol: "BWA", name: "BorgWarner Inc" },
    { symbol: "CAH", name: "Cardinal Health Inc" },
    { symbol: "CBOE", name: "Cboe Global Markets Inc" },
    { symbol: "CDAY", name: "Ceridian HCM Holding Inc" },
    { symbol: "CEG", name: "Constellation Energy Corp" },
    { symbol: "CFG", name: "Citizens Financial Group Inc" },
    { symbol: "CHKP", name: "Check Point Software Technologies Ltd" },
    { symbol: "CINF", name: "Cincinnati Financial Corp" },
    { symbol: "CMS", name: "CMS Energy Corp" },
    { symbol: "COF", name: "Capital One Financial Corp" },
    { symbol: "COO", name: "The Cooper Companies Inc" },
    { symbol: "CPB", name: "Campbell Soup Co" },
    { symbol: "CRL", name: "Charles River Laboratories International Inc" },
    { symbol: "CSGP", name: "CoStar Group Inc" },
    { symbol: "CZR", name: "Caesars Entertainment Inc" },
    { symbol: "DTE", name: "DTE Energy Co" },
    { symbol: "DXC", name: "DXC Technology Co" },
    { symbol: "EA", name: "Electronic Arts Inc" },
    { symbol: "EFX", name: "Equifax Inc" },
    { symbol: "EIX", name: "Edison International" },
    { symbol: "ENPH", name: "Enphase Energy Inc" },
    { symbol: "ESS", name: "Essex Property Trust Inc" },
    { symbol: "EXC", name: "Exelon Corp" },
    { symbol: "EXPD", name: "Expeditors International of Washington Inc" },
    { symbol: "FDS", name: "FactSet Research Systems Inc" },
    { symbol: "FE", name: "FirstEnergy Corp" },
    { symbol: "FTNT", name: "Fortinet Inc" },
    { symbol: "GPN", name: "Global Payments Inc" },
    { symbol: "HAL", name: "Halliburton Co" },
    { symbol: "HCA", name: "HCA Healthcare Inc" },
    { symbol: "HES", name: "Hess Corp" },
    { symbol: "HIG", name: "Hartford Financial Services Group Inc" },
    { symbol: "HII", name: "Huntington Ingalls Industries Inc" },
    { symbol: "HLT", name: "Hilton Worldwide Holdings Inc" },
    { symbol: "HPE", name: "Hewlett Packard Enterprise Co" },
    { symbol: "HPQ", name: "HP Inc" },
    { symbol: "HWM", name: "Howmet Aerospace Inc" },
    { symbol: "IFF", name: "International Flavors & Fragrances Inc" },
    { symbol: "IP", name: "International Paper Co" },
    { symbol: "IPG", name: "Interpublic Group of Companies Inc" },
    { symbol: "JCI", name: "Johnson Controls International plc" },
    { symbol: "KIM", name: "Kimco Realty Corp" },
    { symbol: "KMB", name: "Kimberly-Clark Corp" },
    { symbol: "KMI", name: "Kinder Morgan Inc" },
    { symbol: "KMX", name: "CarMax Inc" },
    { symbol: "KR", name: "Kroger Co" },
    { symbol: "KSS", name: "Kohl's Corp" },
    { symbol: "LVS", name: "Las Vegas Sands Corp" },
    { symbol: "MAA", name: "Mid-America Apartment Communities Inc" },
    { symbol: "MCO", name: "Moody's Corp" },
    { symbol: "MGM", name: "MGM Resorts International" },
    { symbol: "MKC", name: "McCormick & Co Inc" },
    { symbol: "MPWR", name: "Monolithic Power Systems Inc" },
    { symbol: "MRNA", name: "Moderna Inc" },
    { symbol: "MSCI", name: "MSCI Inc" },
    { symbol: "MTB", name: "M&T Bank Corp" },
    { symbol: "NCLH", name: "Norwegian Cruise Line Holdings Ltd" },
    { symbol: "NEM", name: "Newmont Corp" },
    { symbol: "NI", name: "NiSource Inc" },
    { symbol: "NOC", name: "Northrop Grumman Corp" },
    { symbol: "NSC", name: "Norfolk Southern Corp" },
    { symbol: "NTAP", name: "NetApp Inc" },
    { symbol: "NTRS", name: "Northern Trust Corp" },
    { symbol: "NUE", name: "Nucor Corp" },
    { symbol: "OKE", name: "ONEOK Inc" },
    { symbol: "OMC", name: "Omnicom Group Inc" },
    { symbol: "ON", name: "ON Semiconductor Corp" },
    { symbol: "PAYC", name: "Paycom Software Inc" },
    { symbol: "PENN", name: "Penn Entertainment Inc" },
    { symbol: "PKI", name: "PerkinElmer Inc" },
    { symbol: "PFG", name: "Principal Financial Group Inc" },
    { symbol: "PPL", name: "PPL Corp" },
    { symbol: "PRU", name: "Prudential Financial Inc" },
    { symbol: "PTC", name: "PTC Inc" },
    { symbol: "PVH", name: "PVH Corp" },
    { symbol: "RCL", name: "Royal Caribbean Group" },
    { symbol: "RJF", name: "Raymond James Financial Inc" },
    { symbol: "ROK", name: "Rockwell Automation Inc" },
    { symbol: "ROL", name: "Rollins Inc" },
    { symbol: "SJM", name: "The J.M. Smucker Co" },
    { symbol: "SNA", name: "Snap-on Inc" },
    { symbol: "SNOW", name: "Snowflake Inc" },
    { symbol: "SOFI", name: "SoFi Technologies Inc" },
    { symbol: "SQ", name: "Square Inc" },
    { symbol: "SWKS", name: "Skyworks Solutions Inc" },
    { symbol: "SYF", name: "Synchrony Financial" },
    { symbol: "TROW", name: "T. Rowe Price Group Inc" },
    { symbol: "TTD", name: "The Trade Desk Inc" },
    { symbol: "UDR", name: "UDR Inc" },
    { symbol: "ULTA", name: "Ulta Beauty Inc" },
    { symbol: "URI", name: "United Rentals Inc" },
    { symbol: "VFC", name: "V.F. Corp" },
    { symbol: "VICI", name: "VICI Properties Inc" },
    { symbol: "WAB", name: "Wabtec Corp" },
    { symbol: "WMB", name: "Williams Companies Inc" },
    { symbol: "WYNN", name: "Wynn Resorts Ltd" },
    { symbol: "XYL", name: "Xylem Inc" },
    { symbol: "YUM", name: "Yum! Brands Inc" },
    { symbol: "ZBRA", name: "Zebra Technologies Corp" }
];
